### ISSUE TITLE
the O in globles 

### ISSUE THREAD

**Issue by d7eeem** [mvllow/nvim#2]
Hi,
Sorry to about opening the issue but i just discover your repo in the file  lua/globals.lua you have a capital O, where are you declaring it or is it already declared in nvim core?

**Comment by mvllow** [comment]
No worries! `O` is being set in `lua/globals.lua`. It's not a special letter or anything, just a convention I picked up from looking at LunarVim 😌

**Comment by d7eeem** [comment]
Aha Thank you.
